apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rizz-and-compliance

commonLabels:
  aadpodidbinding: summerstudents-backend

# choose the resource you want do deploy. vippsService, Vibe (cron), or both    
resources:
  - summerstudents-backend-service.yaml
  - openApiSwagger/

configurations:
  - kustomizeconfig/vippsservice-image.yaml
  - kustomizeconfig/apim-configuration.yaml
