apiVersion: vops.vipps.io/v1
kind: VippsService
metadata:
  name: summerstudents-backend
spec:
  container:
    env:
      - name: HOST
        value: "0.0.0.0"
      - name: PORT
        value: "8080"
      - name: APP_ID
        value: ""
      - name: ENV
        value: "PROD"
